export const data = {
  products: [
    {
      name: "White Shirt",
      category: "Shirts",
      image: "/images/3-white.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A nice white shirt",
      slug: "white-shirt",
    },
    {
      name: "Black Shirt",
      category: "Shirts",
      image: "/images/8.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A nice white shirt",
      slug: "black-shirt",
    },
    {
      name: "Ash Shirt",
      category: "Shirts",
      image: "/images/3.jpg",
      price: 50,
      brand: "Nike",
      rating: 4,
      numReviews: 10,
      countInStock: 10,
      description: "A nice white shirt",
      slug: "ash-shirt",
    },
    {
      name: "Band",
      category: "bands",
      image: "/images/7.jpg",
      price: 70,
      brand: "Oliver",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A nice band",
      slug: "band",
    },
    {
      name: "red Shirt",
      category: "Shirts",
      image: "/images/4.jpg",
      price: 70,
      brand: "Varsace",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A nice white shirt",
      slug: "red-shirt",
    },
    {
      name: "wrist-band",
      category: "bands",
      image: "/images/2.jpg",
      price: 70,
      brand: "Varsace",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A nice white shirt",
      slug: "wrist-band",
    },
  ],
};
